version: '3.3'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: VisitorPlacementTool
    ports:
      - "5555:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
  #pgadmin:
  #  image: dpage/pgadmin4
  #  restart: unless-stopped
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: root
  #  ports:
  #    - "5050:80"